#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

num=1
while [ $num -le 10 ]; do
	if [ $num -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	(( num ++ ))
done
