#!/usr/bin/env bash
# Bash script that uses ssh to connect to a server
# private key ~/.ssh/school; user ubuntu; host IP given as 34.207.63.215

# Server details
server_ip="34.207.63.215"
user="ubuntu"
private_key="~/.ssh/school"

# SSH connection using single-character flags
ssh -i "$private_key" "$user"@"$server_ip"
